# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adding a Gallery to Jekyll
email: dcparker88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A fun website to share photos from the Parker family and their many adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://parker.camera/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  parker-camera

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
